name: Release
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Install Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: install deps
        run: |
          sudo apt install gnome-keyring
          make install-deps

      - name: install twine
        run: pip install --upgrade pip && pip install twine

      - name: build
        run: make build

      - name: check build
        run: twine check dist/*

      - name: set poetry credentials
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: publish
        run: poetry publish
