name: Release
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Install Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      
      - name: install gnome-keyring
        run: |
          sudo apt-get update
          echo "Available versions of gnome-keyring:"
          apt-cache policy gnome-keyring

          echo "Installing default candidate version"
          sudo apt-get install -y gnome-keyring

      - name: install deps
        run: make install-deps

      - name: install twine
        run: pip install --upgrade pip && pip install twine

      - name: build
        run: make build

      - name: check build
        run: twine check dist/*

      - name: set poetry credentials
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: publish
        run: poetry publish
