name: PR validation
on: pull_request
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      APIGEE_USERNAME: ${{ secrets.APIGEE_USERNAME }}
      APIGEE_PASSWORD: ${{ secrets.APIGEE_PASSWORD }}
      APIGEE_OTP_KEY: ${{ secrets.APIGEE_OTP_KEY }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: install
        run: make install-deps build

      - name: get otp
        id: otp
        run: echo ::set-output name=key::$(poetry run python scripts/otp.py ${APIGEE_USERNAME} ${APIGEE_OTP_KEY})


      - name: Install get_token
        run: |
          curl https://login.apigee.com/resources/scripts/sso-cli/ssocli-bundle.zip -O
          unzip ssocli-bundle.zip

      - name: Get APIGEE access token
        id: apigee
        run: |
          echo ::add-mask $(SSO_LOGIN_URL=https://login.apigee.com ./get_token -u ${APIGEE_USERNAME}:${APIGEE_PASSWORD} -m ${{ steps.otp.outputs.key }})
          echo ::set-output name=token::$(SSO_LOGIN_URL=https://login.apigee.com ./get_token -u ${APIGEE_USERNAME}:${APIGEE_PASSWORD} -m ${{ steps.otp.outputs.key }})

      - name: test
        run: APIGEE_ACCESS_TOKEN=${{ steps.apigee.outputs.token }} make test

  check-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          path: pr

      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: refs/heads/main
          path: main


      - name: Extract current version
        id: versions
        run: |
          echo ::set-output name=current::$(grep version main/pyproject.toml | awk -F\" '{print $2}')
          echo ::set-output name=candidate::$(grep version pr/pyproject.toml | awk -F\" '{print $2}')

      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Compare versions
        run: python pr/scripts/compare_version.py ${{ steps.versions.outputs.current }} ${{ steps.versions.outputs.candidate }}
