name: PR validation
on: 
  pull_request
jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Check the Src folder for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'src/pytest_nhsd_apim/**'


  integration-tests:
    needs: check_changes
    if: needs.check_changes.filters.src == 'true'
    runs-on: ubuntu-latest
    env:
      APIGEE_USERNAME: ${{ secrets.APIGEE_USERNAME }}
      APIGEE_PASSWORD: ${{ secrets.APIGEE_PASSWORD }}
      APIGEE_OTP_KEY: ${{ secrets.APIGEE_OTP_KEY }}
    steps:

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: install
        run: |
          sudo apt-get update
          echo "Available versions of gnome-keyring:"
          apt-cache policy gnome-keyring

          echo "Installing default candidate version"
          sudo apt-get install -y gnome-keyring

      - name: get otp
        id: otp
        run: echo ::set-output name=key::$(poetry run python scripts/otp.py ${APIGEE_USERNAME} ${APIGEE_OTP_KEY})

      - name: Install get_token
        run: |
          curl https://login.apigee.com/resources/scripts/sso-cli/ssocli-bundle.zip -O
          unzip ssocli-bundle.zip

      - name: Get APIGEE access token
        id: apigee
        run: |
          echo ::add-mask $(SSO_LOGIN_URL=https://login.apigee.com ./get_token -u ${APIGEE_USERNAME}:${APIGEE_PASSWORD} -m ${{ steps.otp.outputs.key }})
          echo ::set-output name=token::$(SSO_LOGIN_URL=https://login.apigee.com ./get_token -u ${APIGEE_USERNAME}:${APIGEE_PASSWORD} -m ${{ steps.otp.outputs.key }})
      
      - name: Install Poetry
        run: |
          make install-deps
          make build-install
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
            
      - name: test
        run: APIGEE_ACCESS_TOKEN=${{ steps.apigee.outputs.token }} make test

  check-version-bump:
    needs: check_changes
    if: needs.check_changes.filters.src == 'true'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          path: pr

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: refs/heads/main
          path: main

      - name: Extract current version
        id: versions
        run: |
          echo ::set-output name=current::$(grep version main/pyproject.toml | awk -F\" '{print $2}')
          echo ::set-output name=candidate::$(grep version pr/pyproject.toml | awk -F\" '{print $2}')

      - name: Install Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Compare versions
        run: python pr/scripts/compare_version.py ${{ steps.versions.outputs.current }} ${{ steps.versions.outputs.candidate }}